// <auto-generated />
using System;
using BusControl.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusControl.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260531233859_AdicionandoTabelaUsuario")]
    partial class AdicionandoTabelaUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BusControl.Models.UsuarioModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<byte[]>("SenhaSalt")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.HasKey("id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("BusControl.Models.ViagensModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("dataHoraRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("destinoViagem")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("diaHoraChegada")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("diaHoraSaida")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("nomeMotorista")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nomeOnibus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("quantidadePassageiros")
                        .HasColumnType("int");

                    b.Property<int>("rotaViagem")
                        .HasColumnType("int");

                    b.Property<decimal>("valorViagem")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("id");

                    b.ToTable("Viagens");
                });
#pragma warning restore 612, 618
        }
    }
}
