// <auto-generated />
using System;
using BusControl.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusControl.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260607051348_AlterarStatusMotorista")]
    partial class AlterarStatusMotorista
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BusControl.Models.MotoristaModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Motoristas");
                });

            modelBuilder.Entity("BusControl.Models.UsuarioModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<byte[]>("SenhaSalt")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.HasKey("id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("BusControl.Models.VeiculoModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("categoria")
                        .HasColumnType("int");

                    b.Property<DateTime>("dataHoraRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("marcaVeiculo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nomeVeiculo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("placaVeiculo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("BusControl.Models.ViagemModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("destino")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("motorista")
                        .HasColumnType("int");

                    b.Property<int>("quantidadeParadas")
                        .HasColumnType("int");

                    b.Property<int>("quantidadePassageiros")
                        .HasColumnType("int");

                    b.Property<decimal>("valorViagem")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("veiculo")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Viagens");
                });
#pragma warning restore 612, 618
        }
    }
}
